# Cấu hình chung KẻSátNhân
min-players: 8
max-players: 10
countdown-seconds: 30
full-start-short-seconds: 5
hit-reset-seconds: 10
end-delay-seconds: 10
force-start-min: 2
# Clone map tam khi het map ranh
max-temp-clones: 3
clone-retry-delay-seconds: 30
